osx_image: xcode9.3
language: swift
cache:
  - cocoapods

before_install:
  - cd Example
  - pod repo update
  - pod install

script:
  - |
    xcodebuild \
    -workspace Example.xcworkspace \
    -scheme AllUnitTests_iOS \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 8' \
    build \
    test \
    ONLY_ACTIVE_ARCH=YES \
    CODE_SIGNING_REQUIRED=NO \
    | xcpretty

branches:
  only:
    - develop
